version: '3.8'

services:
  halina-app:
    build:
      context: .
    ports:
      - "5000:80"
    environment:
      - NATS_HOST=nats
      - NATS_PORT=4222
      - TELESCOPES_NAME=${TELESCOPES_NAME}
      - EMAILS=${EMAILS}
      - TIMEZONE=${TIMEZONE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - FROM_EMAIL=${FROM_EMAIL}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
    networks:
      - halina-net

networks:
  halina-net:
    external: true
