version: '3.8'

services:
  halina-app:
    build: .
    depends_on:
      - nats
    environment:
      - NATS_HOST=nats
      - NATS_PORT=4222
      - TELESCOPES_NAME=${TELESCOPES_NAME}
      - EMAILS_TO=${EMAILS_TO}
      - TIMEZONE=${TIMEZONE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - FROM_EMAIL=${FROM_EMAIL}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - halina-net

networks:
  halina-net:
    external: true
