version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:80"
    environment:
      - NATS_HOST=${NATS_HOST}
      - NATS_PORT=${NATS_PORT}
      - TELESCOPES_NAME=${TELESCOPES_NAME}
      - EMAILS_TO=${EMAILS_TO}
      - TIMEZONE=${TIMEZONE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - FROM_EMAIL=${FROM_EMAIL}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
